name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
          
    - name: Install dependencies
      run: sudo apt install -y python3 python3-gi gir1.2-caja-2.0 python3-caja python3-pip ffmpeg && pip3 install ffmpeg-python
      
    - name: Build the package
      run: make
      
    - name: Publish Package to Releases
      uses: xresloader/upload-to-github-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: "*.deb"
        tags: false
        draft: false
      
